sudo: required
services:
  - docker

before_install:
  - docker build -t dada1008/docker-react -f Dockerfile.dev .

script:
  - docker run dada1008/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "dada-docker-react"
  env: "DadaDockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-360506821424"
  bucket_path: "dada-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"